NumPy, short for Numerical Python, is a key foundational package for numerical computing. Other scientific packages often use its <i>ndarray</i> objects (N-dimensional arrays that we often just call 'arrays') as a 'lingua franca' for data exchange. Most of its concepts are transferable to pandas.<br>
Overview: an <i>ndarray</i> is an efficient multidimensional array that has fast arithmetic and flexible <i>broadcasting</i>. NumPy offers vectorized math functions, tools for reading and writing array data and working with memory-mapped files, linear algebra, RNG, Fourier transform, and a C API to pass data to external libraries written in a low-level language. It thus helps wrap legacy C/ C++/ FORTRAN codebases.<br>
NumPy does not itself offer modeling or scientific functionality, but knowing its arrays and array-oriented computing helps in using other tools, eg pandas. NumPy is a large topic, some more advanced ideas like broadcasting are deferred.<br>
For most data analysis work, relevant concepts are: data cleaning, subsetting, filtering, transformation, and computations. Common algorithms (sorting, unique, set operations). Descriptive statistics and aggregating/ summarizing data. Data alignment and relational data manipulations to merge and join heterogeneous datasets. Express conditional logic as array expressions instead of loops and <i>if/ else</i>.<br>
NumPy is the foundation for numerical data processing, but most people use pandas as the basis for statistics and analytics, esp on tabular data. Pandas also has some domain-specific tools (eg time series) that NumPy does not.<br>
How NumPy is efficient: it stores data in a contiguous block of memory, independent of other built-in Python objects. Its library of algorithms is written in C and can operate on this memory without type checking or other overhead with regular interpreted Python code. Its arrays use less memory than built-in Python sequences.<br>
Below is the standard way to load NumPy. It is not recommended to use 'from numpy import *' and avoid the np prefix since many of its functions conflict with built-in Python (eg <i>max</i>)



In [1]:
import numpy as np
import matplotlib.pyplot as plt

We show NumPy's superior performance. <i>np.arange</i> is its version of <i>range</i>, with the same arguments <i>start, stop, step</i>, except np allows non-integers

In [ ]:
my_arr = np.arange(1_000_000)
#my_list = list(range(1_000_000))
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in range(1_000_000)]

2 ms ± 814 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
99.5 ms ± 21.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


The ndarray (or array) allows 1+ dimensions, and is a fast, flexible container for big datasets. It enables batch computations, most elementary are addition and scalar multiplication. Its data must be homogeneous: all of the same type (usually float64 as below), see it with <i>dtype</i>. Its <i>shape</i> (tuple) gives the length along each dimension.
Create 1 with <i>np.array</i> (a function, <i>np.ndarray</i> is a class), which accepts any iterable (including another array, but usually a list) which is turned into a new array. Nested sequences become multidimensional arrays. By default, it infers the best <i>dtype</i> based on what you pass in.

In [ ]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data.shape #(2,3)
data.ndim #same: len(data.shape)
data.dtype #dtype('float64')
data * 8 #same: 8*data
data + data #entry by entry
data+6 #same 6+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

Many functions make new arrays, eg <i>np.arange</i> as we have seen, <i>np.zeros, np.ones, np.empty</i> make arrays with the input shape where each entry is (resp) 0, 1, or uninitialized (assume nothing about its initial 'values' - use only if you intend to populate them later)

In [ ]:
np.ones(shape=10)
np.zeros((3, 6))
np.empty((2, 3, 2))

array([[[6.54892381e-310, 0.00000000e+000],
        [2.10077583e-312, 6.79038654e-313],
        [2.22809558e-312, 2.14321575e-312]],

       [[2.35541533e-312, 6.79038654e-313],
        [2.22809558e-312, 2.14321575e-312],
        [2.46151512e-312, 2.41907520e-312]]])

The same functions with <i>_like</i> make a new array with all 0s (resp 1s or uninitialized values) with the same attributes as the input array <i>a</i>, notably the dtype and shape, unless you pass arguments to override them. Aside: the 1st argument of <i>np.empty_like</i> is positional only

In [ ]:
np.ones_like(a=data)
np.zeros_like(a=data)
np.empty_like(data)

array([[0., 0., 0.],
       [0., 0., 0.]])

<table border="1" cellpadding="6" cellspacing="0">
  <thead>
    <tr><th>Function</th><th>Description</th></tr>
  </thead>
  <tbody>
    <tr><td>array</td>
    <td>Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type<br>
    or explicitly specifying a data type; copies the input data by default</td></tr>
    <tr><td>asarray</td>
    <td>Convert input to ndarray, but do not copy if the input is already an ndarray</td></tr>
    <tr><td>arange</td>
    <td>Like the built-in range but returns an ndarray instead of a list</td></tr>
    <tr><td>ones, ones_like</td>
    <td>Produce an array of all 1s with the given shape and data type; ones_like takes another array and produces<br>
    a ones array of the same shape and data type</td></tr>
    <tr><td>zeros, zeros_like</td>
    <td>Like ones and ones_like but producing arrays of 0s instead</td></tr>
    <tr><td>empty, empty_like</td>
    <td>Create new arrays by allocating new memory, but do not populate with any values like ones and zeros</td></tr>
    <tr><td>full, full_like</td>
    <td>Produce an array of the given shape and data type with all values set to the indicated "fill value";<br>
    full_like takes another array and produces a filled array of the same shape and data type</td></tr>
    <tr><td>eye, identity</td>
    <td>Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)</td></tr>
  </tbody>
</table>

<i>np.asarray</i> is similar to <i>np.array</i> (and roughly speaking, matches the latter with copy=False) except when the input is already an array, it will return that array, not make a new copy

In [ ]:
qj=np.array(object=data)
jx=np.array(object=data, copy=False)
q=np.asarray(a=data)
qj is data #False
jx is data #True
q is data #True

True

In [ ]:
#Use <i>np.full(_like)</i> to make a new array with a custom value for all entries
np.full(shape=data.shape, fill_value=3)
np.full_like(a=data, fill_value=6)

array([[6., 6., 6.],
       [6., 6., 6.]])

More on dtypes: for numerics, the digits in the suffix give how many bits are used, eg <i>np.float64</i> (same: dtype='f8') means 64 bits = 8 bytes, ie double precision. <i>np.int8</i> (same dtype='i1') is an 8 bit integer, from -128 to 127.  <i>np.uint8</i> (same dtype='u1') is an unsigned 8 bit integer, from 0 to 255. <i>np.complex64</i> (same dtype='c8') is a 64 bit complex number, but that means 32 bits are devoted to the real and imaginary parts, so single precision overall.<br>
For fixed length strings, use eg dtype='S_' (ASCII strings, 1 byte per character), where _ is how many bytes to use, or dtype='U_' (unicode strings. Python may display it as eg dtype('<U6'), do not worry about the <). Use dtype=np.bytes_ to infer the length based on the longest entry (trying to use longer strings later can lead to truncation. Pandas is better behaved wrt variable length strings). For variable length strings, use dtype=np.object_ (same dtype='O'), but this also allows any object.<br>
You can also input base Python types into dtype and NumPy will alias it to its own equivalent, eg float -> np.float64

In [ ]:
arr=np.array([1, 2, 3], dtype=np.bool) #coerce to logical
arb=np.array([1, ']', 3], dtype='O')
#ari=np.array([1, 136, 3], dtype=np.int8) #OverflowError
arb

OverflowError: Python integer 136 out of bounds for int8

<table border="1" cellpadding="6" cellspacing="0">
  <thead>
    <tr><th>Type</th><th>Type code</th><th>Description</th></tr>
  </thead>
  <tbody>
    <tr><td>int8, uint8</td><td>i1, u1</td><td>Signed and unsigned 8-bit (1 byte) integer types</td></tr>
    <tr><td>int16, uint16</td><td>i2, u2</td><td>Signed and unsigned 16-bit integer types</td></tr>
    <tr><td>int32, uint32</td><td>i4, u4</td><td>Signed and unsigned 32-bit integer types</td></tr>
    <tr><td>int64, uint64</td><td>i8, u8</td><td>Signed and unsigned 64-bit integer types</td></tr>
    <tr><td>float16</td><td>f2</td><td>Half-precision floating point</td></tr>
    <tr><td>float32</td><td>f4 or f</td><td>Standard single-precision floating point; compatible with C float</td></tr>
    <tr><td>float64</td><td>f8 or d</td><td>Standard double-precision floating point; compatible with C double<br>
    and Python float object</td></tr>
    <tr><td>float128</td><td>f16 or g</td><td>Extended-precision floating point</td></tr>
    <tr><td>complex64, complex128, complex256</td><td>c8, c16, c32</td><td>Complex numbers represented by two 32, 64, or 128 floats, respectively</td></tr>
    <tr><td>bool</td><td>?</td><td>Boolean type storing True and False values</td></tr>
    <tr><td>object</td><td>O</td><td>Python object type; a value can be any Python object</td></tr>
    <tr><td>string_</td><td>S</td><td>Fixed-length ASCII string type (1 byte per character); for example, to create a string<br>
    data type with length 10, use 'S10'</td></tr>
    <tr><td>unicode_</td><td>U</td><td>Fixed-length Unicode type (number of bytes platform specific); same specification semantics<br>
    as string_ (e.g., 'U10')</td></tr>
  </tbody>
</table>

Use the <i>astype</i> method to cast arrays to another dtype

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int8) #truncates decimals

array([ 3, -1, -2,  0, 12, 10], dtype=int8)

In [ ]:
numeric_strings = np.array(["1.25", "-9.63", "42"], dtype=np.bytes_)
numeric_strings.dtype #dtype('S5')
#numeric_strings.astype(float)

dtype('<U5')

In [ ]:
#arithmetic on equally shaped arrays occurs element-wise
arr = np.array([[1., 2., 3.], [4., 5., 6.]]) #float64
ar2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr * ar2
#arithmetic with scalars propagates it to each element
1/arr
#comparisons between 1 array and another equally shaped or a scalar gives a boolean array
qjx=arr>ar2 #bool
arr>3

array([[False, False, False],
       [ True,  True,  True]])

While beyond our scope, <i>broadcasting</i> involves operations between differently shaped arrays<br>
For the most part, indexing and slicing with 1D arrays behaves just like with lists

In [3]:
lst=list(range(10))
arr = np.array(lst)
arr[5] #np.int64(5)
arr[5].item() #cleaner, or print(arr[5])
arr[5:8]
#lst[5:8]=12 #TypeError
arr[5:8] = 12 #value is propagated/ broadcast

A key difference between list/ array slicing is that the former always makes a copy, while modifying an array slice also modifies the original. Pandas is like this too. The reason is better performance/ memory than doing copying

In [ ]:
arr_slice = arr[5:8] #a view of a slice
asc=arr[5:8].copy() #a copy of a slice
arr_slice
arr_slice[1] = 123
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [ ]:
#use the bare slice to reassign all values
arr_slice[:] = 64
arr

With n dimensional arrays, the element at each index is n-1 dimensional. Individual elements can be accessed recursively, or more simply by a comma separated list of indices. If you omit later indices, the return value is a lower dimensional array with all data along the higher dimensions. In 2D, think of the rows as axis 0 and the columns as axis 1

In [2]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2] #last row
arr2d[0][2] #recursive
arr2d[0, 2] #same, easier, fails with a list of lists

np.int64(3)

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[1, 0]

In [ ]:
#slice along any axis, : by itself means keep whole axis
arr2d[:2] #shape (2,3)
arr2d[:2, 1:] #shape (2,2)
arr2d[:,:1] #shape (3,1)
arr2d[:,0] #shape (3,)
arr2d[:2, 1:] = 0 #assign to a slice expression
arr2d

array([1, 4, 7])

Boolean indexing is just like R's subsetting by logical. The Boolean sequence must be the same length. It can be mixed and matched with slices and integers

In [ ]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])
names=='Bob' #vectorized comparison
data[names == "Bob"] #Boolean indexing
data[names == "Bob",1]
data[names == "Bob",1:]

array([[7],
       [0]])

In [ ]:
names != "Bob"
~(names == "Bob") #~ is element wise negation in np
#~list(names == "Bob") #fails
qjx=data[~(names == "Bob")] #Boolean indexing makes a copy, not view
qjx[:]=6
data #unchanged

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

Use &, |, ~ to apply 'and', 'or', 'not' element wise to arrays. Use parentheses since these take higher precedence in order of operations than comparisons

In [ ]:
cond = names == "Bob"
mask = cond | (names == "Will")
mask
data[mask]

In [ ]:
True & False #bitwise, 1st converted to int
True | False
#~True #-2. For negation use 'not'

True

In [ ]:
#modify a subset, much harder without Boolean indexing
data[data < 0] = 0
#modify higher dimensions with a 1D Boolean array
data[names != "Joe"] = 7
data

<i>Fancy indexing</i> in numpy means indexing via arrays of integers, this subsets the elements in the given order. Negative indices select elements from the end. Passing multiple index arrays returns a 1D array with elements corresponding to each tuple of indices. <i>np.take()</i> is also a way to index

In [ ]:
qjx=arr[[4, -3, 1, 6]] #copy, not view
arr[[4, -3, 1, 6]]=8 #reassign values
qjx #unchanged
arr2d[[0,1,0], [1, 0, 2]] #1D
arr2d[[0,1,0]][:, [1, 0, 2]] #'expected' value for previous line

In [ ]:
np.take(a=arr, indices=[4, -3, 1, 6])
np.take(a=arr2d, indices=[4, -3, 1, 6]) #flatten before taking
np.take(a=arr2d, indices=[2, 1],axis=1)

Transposing is a special kind of reshaping. It is a special case of <i>np.swapaxes</i>, which takes the 2 axes as ints and swaps them. Both return a view, not copy. Use <i>np.dot</i> for matrix multiplication, or more simply the infix operator '@' (* would be element wise multiplication)

In [ ]:
qjx=arr2d.T #same arr2d.transpose() or np.transpose(arr2d)
arr2d.swapaxes(0, 1) #same np.swapaxes(arr2d, 0, 1)
qjx[2,1]=36
arr2d #changed
arr2d.T @ arr2d #same np.dot(arr2d.T, arr2d) or arr2d.T.dot(arr2d)
arr2d @ np.array([3,6,8]) #matrix vector multiplication

array([[ 1,  2,  3],
       [ 4,  5, 36],
       [ 7,  8,  9]])

The <i>np.random</i> module, more powerful than base Python's <i>random</i> module, efficiently generates arrays of values sampled from a diverse set of probability distributions (base <i>random</i> generates 1 at a time). The values are pseudorandom (not truly random) from a configurable but deterministic RNG. A function like <i>np.random.standard_normal</i> uses <i>np.random's</i> default RNG, but you can use an explicit 1

In [ ]:
samples = np.random.standard_normal(size=(4, 4))
samples = np.random.normal(size=(4, 4)) #same
samples

array([[ 6.37733998,  2.98370497,  5.98552826,  5.57687283],
       [ 8.02789857,  3.90984236, 13.93559648,  3.86568358],
       [ 8.21851492,  5.12678683,  8.38901548,  8.68498426],
       [ 9.40681242,  6.97695232,  5.11607344,  8.62482486]])

In [ ]:
rng = np.random.default_rng(seed=12345) #explicit RNG
data = rng.standard_normal((2, 3))
type(rng)

numpy.random._generator.Generator

In [ ]:
from random import normalvariate
N = 1_000_000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.standard_normal(N)
%timeit rng.standard_normal(N)

777 ms ± 224 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
30.2 ms ± 645 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
16.4 ms ± 1.92 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


<table border="1" cellpadding="6" cellspacing="0">
  <thead>
    <tr><th>Method</th><th>Description</th></tr>
  </thead>
  <tbody>
    <tr><td>permutation</td>
    <td>Return a random permutation of a sequence, or return a permuted range</td></tr>
    <tr><td>shuffle</td>
    <td>Randomly permute a sequence in place</td></tr>
    <tr><td>uniform</td>
    <td>Draw samples from a uniform distribution</td></tr>
    <tr><td>integers</td>
    <td>Draw random integers from a given low-to-high range</td></tr>
    <tr><td>standard_normal</td>
    <td>Draw samples from a normal distribution with mean 0 and standard deviation 1</td></tr>
    <tr><td>binomial</td>
    <td>Draw samples from a binomial distribution</td></tr>
    <tr><td>normal</td>
    <td>Draw samples from a normal (Gaussian) distribution</td></tr>
    <tr><td>beta</td>
    <td>Draw samples from a beta distribution</td></tr>
    <tr><td>chisquare</td>
    <td>Draw samples from a chi-square distribution</td></tr>
    <tr><td>gamma</td>
    <td>Draw samples from a gamma distribution</td></tr>
    <tr><td>uniform</td>
    <td>Draw samples from a uniform [0, 1) distribution</td></tr>
  </tbody>
</table>

A universal function (aka ufunc) performs element wise operations, basically a vectorized wrapper. Unary examples (take 1 argument) are <i>np.exp, np.sqrt</i>. Binary examples are <i>np.add, np.maximum</i>. Less commonly, a ufunc returns multiple arrays, eg <i>np.modf</i>, which gives the fractional and integer parts element wise. New ufuncs are continuously added to NumPy: see the documentation

In [ ]:
arj = np.arange(10)
np.sqrt(arj)
np.exp(arj)

In [ ]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)
np.add(x, y) #same x+y
np.maximum(x, y)

In [ ]:
int(2/3), int(-2/3)

(0, 0)

In [ ]:
arj = rng.standard_normal(7) * 5
remainder, whole_part = np.modf(arj)
remainder, whole_part.dtype #still float64

(array([-0.83896351,  0.24446401,  0.80529057, -0.76431532,  0.73704827,
         0.84248453, -0.7969359 ]),
 dtype('float64'))

Ufuncs have an out= argument where they can assign results to an existing array instead of make a new 1

In [ ]:
dest = np.zeros_like(x)
#dest=np.exp(x+1) #memory temporarily allocated to store x+1
np.add(x, 1, out=dest)
np.exp(dest, out=dest)
dest

<table border="1" cellpadding="6" cellspacing="0">
  <thead>
    <tr><th>Unary Function</th><th>Description</th></tr>
  </thead>
  <tbody>
    <tr><td>abs, fabs</td><td>Compute the absolute value element-wise for integer, floating-point, or complex values</td></tr>
    <tr><td>sqrt</td><td>Compute the square root of each element (equivalent to arr ** 0.5)</td></tr>
    <tr><td>square</td><td>Compute the square of each element (equivalent to arr ** 2)</td></tr>
    <tr><td>exp</td><td>Compute the exponent ex of each element</td></tr>
    <tr><td>log, log10, log2, log1p</td><td>Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively</td></tr>
    <tr><td>sign</td><td>Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)</td></tr>
    <tr><td>ceil</td><td>Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)</td></tr>
    <tr><td>floor</td><td>Compute the floor of each element (i.e., the largest integer less than or equal to each element)</td></tr>
    <tr><td>rint</td><td>Round elements to the nearest integer, preserving the dtype</td></tr>
    <tr><td>modf</td><td>Return fractional and integral parts of array as separate arrays</td></tr>
    <tr><td>isnan</td><td>Return Boolean array indicating whether each value is NaN (Not a Number)</td></tr>
    <tr><td>isfinite, isinf</td><td>Return Boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively</td></tr>
    <tr><td>cos, cosh, sin, sinh, tan, tanh</td><td>Regular and hyperbolic trigonometric functions</td></tr>
    <tr><td>arccos, arccosh, arcsin, arcsinh, arctan, arctanh</td><td>Inverse trigonometric functions</td></tr>
    <tr><td>logical_not</td><td>Compute truth value of not x element-wise (equivalent to ~arr)</td></tr>
  </tbody>
</table><p>
<table border="1" cellpadding="6" cellspacing="0">
  <thead>
    <tr><th>Binary Function</th><th>Description</th></tr>
  </thead>
  <tbody>
    <tr><td>add</td><td>Add corresponding elements in arrays</td></tr>
    <tr><td>subtract</td><td>Subtract elements in second array from first array</td></tr>
    <tr><td>multiply</td><td>Multiply array elements</td></tr>
    <tr><td>divide, floor_divide</td><td>Divide or floor divide (truncating the remainder)</td></tr>
    <tr><td>power</td><td>Raise elements in first array to powers indicated in second array</td></tr>
    <tr><td>maximum, fmax</td><td>Element-wise maximum; fmax ignores NaN</td></tr>
    <tr><td>minimum, fmin</td><td>Element-wise minimum; fmin ignores NaN</td></tr>
    <tr><td>mod</td><td>Element-wise modulus (remainder of division)</td></tr>
    <tr><td>copysign</td><td>Copy sign of values in second argument to values in first argument</td></tr>
    <tr><td>greater, greater_equal, less, less_equal, equal, not_equal</td><td>Perform element-wise comparison, yielding Boolean array<br>
    (equivalent to infix operators &gt;, &gt;=, &lt;, &lt;=, ==, !=)</td></tr>
    <tr><td>logical_and</td><td>Compute element-wise truth value of AND (&amp;) logical operation</td></tr>
    <tr><td>logical_or</td><td>Compute element-wise truth value of OR (|) logical operation</td></tr>
    <tr><td>logical_xor</td><td>Compute element-wise truth value of XOR (^) logical operation</td></tr>
  </tbody>
</table>

Vectorization means using array expressions instead of explicit loops. If you want to graph a function f(x,y) across a grid of values, <i>np.meshgrid</i> takes each coordinate's values as a 1D sequence, and returns n n-dimensional arrays where taking the values from each at the same fixed position gives the length n coordinate vector. Then you could compute f on those points the same way you'd do if they were scalars. We also preview <i>matplotlib</i>

In [ ]:
points = np.arange(-5, 5, 0.01) # 1e3 equally spaced points
xs, ys = np.meshgrid(points, points)
ys.shape

(1000, 1000)

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)
plt.imshow(z, cmap=plt.cm.gray, extent=[-5, 5, -5, 5])
plt.colorbar()
plt.title("Image plot of $\\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = [(x if c else y)
  for x, y, c in zip(xarr, yarr, cond)]
#the 2nd and 3rd arguments can be scalars
np.where(cond, xarr, yarr) #same but faster and generalizes to higher dimensions

Aggregations (aka reductions) like <i>np.sum, np.mean, np.std</i> are called either via the array instance or top level np. The axis argument optionally gives the axes to aggregate over (by default, the array is 1st flattened). Like in R, <i>np.nan</i> will propagate

In [ ]:
arr = rng.standard_normal((5, 4))
arr.mean() #same np.mean(arr)
arr.sum() #same np.sum(arr)
np.array([]).sum() #0, mean is np.nan

/tmp/ipykernel_12937/2539963207.py:4: RuntimeWarning: Mean of empty slice.
  np.array([]).mean() #0, mean is np.nan
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


np.float64(nan)

In [ ]:
arr[3,1]=np.nan
arr.mean(axis=1) #means per row
arr.sum(axis=0) #sums per column

array([-3.03626016,         nan,  2.33070356,  1.59008783])

<i>np.cumsum, np.cumprod</i> do not aggregate, instead keeping the intermediate cumulative sums/ products

In [ ]:
arr = np.array([1, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()
arr = np.array([[1, 1, 2], [3, np.nan, 5], [6, 7, 8]])
arr.cumsum(axis=0)
arr.cumprod(axis=1)

array([[  1.,   1.,   2.],
       [  3.,  nan,  nan],
       [  6.,  42., 336.]])

<table border="1" cellpadding="6" cellspacing="0">
  <thead>
    <tr><th>Method</th><th>Description</th></tr>
  </thead>
  <tbody>
    <tr><td>sum</td><td>Sum of all the elements in the array or along an axis; zero-length arrays have sum 0</td></tr>
    <tr><td>mean</td><td>Arithmetic mean; invalid (returns NaN) on zero-length arrays</td></tr>
    <tr><td>std, var</td><td>Standard deviation and variance, respectively</td></tr>
    <tr><td>min, max</td><td>Minimum and maximum</td></tr>
    <tr><td>argmin, argmax</td><td>Indices of minimum and maximum elements, respectively</td></tr>
    <tr><td>cumsum</td><td>Cumulative sum of elements starting from 0</td></tr>
    <tr><td>cumprod</td><td>Cumulative product of elements starting from 1</td></tr>
  </tbody>
</table>

Booleans are often coerced to 1/0 in arithmetic operations. <i>np.sum</i> is useful to count how many entries meet some condition

In [ ]:
arr = rng.standard_normal(100)
(arr > 0).sum() # Number of positive values
(arr > 0).sum() # Number of positive values
(arr <= 0).std()
np.exp(arr <= 0)

array([2.719, 2.719, 2.719, 1.   , 2.719, 2.719, 2.719, 2.719, 2.719,
       2.719, 1.   , 2.719, 2.719, 2.719, 2.719, 1.   , 1.   , 2.719,
       2.719, 1.   , 1.   , 1.   , 1.   , 2.719, 1.   , 2.719, 2.719,
       1.   , 1.   , 2.719, 2.719, 1.   , 1.   , 1.   , 2.719, 2.719,
       1.   , 1.   , 1.   , 1.   , 1.   , 2.719, 2.719, 2.719, 2.719,
       1.   , 1.   , 1.   , 1.   , 2.719, 1.   , 2.719, 1.   , 2.719,
       1.   , 1.   , 1.   , 1.   , 2.719, 2.719, 1.   , 2.719, 2.719,
       2.719, 1.   , 1.   , 1.   , 2.719, 2.719, 1.   , 2.719, 2.719,
       2.719, 2.719, 2.719, 1.   , 1.   , 2.719, 2.719, 2.719, 2.719,
       2.719, 1.   , 2.719, 1.   , 1.   , 2.719, 1.   , 1.   , 1.   ,
       1.   , 1.   , 2.719, 1.   , 1.   , 1.   , 2.719, 2.719, 2.719,
       2.719], dtype=float16)

In [ ]:
bools = np.array([False, False, True, False, np.nan])
np.any([3,0]) #non Boolean values allowed
bools.any() #same np.any(bools)
bools.all().item() #use item, else np.False_

False

In [ ]:
arr = rng.standard_normal(8)
arr[6]=np.nan
qjx=arr
np.sort(qjx) #top level method gives new copy, do a reverse slice [::-1] for descending order
qjx.sort() #in place
arr

array([-1.23157125, -1.12557525, -0.86904959, -0.68462384,  0.01995842,
        1.22651896,  2.4024728 ,         nan])

In [ ]:
arr = rng.standard_normal((5, 3))
arr.sort(axis=-1) #sort along last axis (default), per row (axis=1) in this case
arr.sort(axis=0) #sort per column
arr

array([[-1.39228465, -0.36401729,  0.41991549],
       [-1.17073802,  0.23569948,  1.11370559],
       [-1.06952042,  0.40198218,  1.35242893],
       [-0.71297448,  0.91045932,  1.43473399],
       [ 0.13796965,  1.23231538,  1.81411281]])

In [ ]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names) #sorted unique values, no 'missing value' like np.nan for unicode dtype
sorted(set(names)) #slower, returns list
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4, np.nan])
np.unique(ints)

array([ 1.,  2.,  3.,  4., nan])

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, np.nan, 6])
np.isin(values, [2, 3, 6, np.nan]) #np.nan becomes False
#[item in [2,3,6, np.nan] for item in values] #analogous
#see also np.union1d, np.setdiff1d, np.setxor1d
np.intersect1d(values, ints) #np.nan ignored

array([2., 3.])

In [ ]:
np.all([']','']) #non Boolean values allowed
#sorted([6,8,None])
qjx=arr
qjx.reshape((3,5))
arr

array([[-1.39228465, -0.36401729,  0.41991549],
       [-1.17073802,  0.23569948,  1.11370559],
       [-1.06952042,  0.40198218,  1.35242893],
       [-0.71297448,  0.91045932,  1.43473399],
       [ 0.13796965,  1.23231538,  1.81411281]])

<table border="1" cellpadding="6" cellspacing="0">
  <thead>
    <tr><th>Method</th><th>Description</th></tr>
  </thead>
  <tbody>
    <tr><td>unique(x)</td><td>Compute the sorted, unique elements in x</td></tr>
    <tr><td>intersect1d(x, y)</td><td>Compute the sorted, common elements in x and y</td></tr>
    <tr><td>union1d(x, y)</td><td>Compute the sorted union of elements</td></tr>
    <tr><td>in1d(x, y)</td><td>Compute a Boolean array indicating whether each element of x is contained in y</td></tr>
    <tr><td>setdiff1d(x, y)</td><td>Set difference, elements in x that are not in y</td></tr>
    <tr><td>setxor1d(x, y)</td><td>Set symmetric differences; elements that are in either of the arrays, but not both</td></tr>
  </tbody>
</table>

NumPy can save/ load data in text/ binary formats. The .npy and .npz file extensions are special to NumPy (other applications will struggle with them). Arrays are saved by default in an uncompressed raw binary format. <i>np.load</i> does not create variables, assign them if you need them

In [ ]:
arr = np.arange(10)
np.save(file="some_array", arr) #.npy added onto file name if not already

In [ ]:
arr=']qjx'
qjx=np.load("some_array.npy")
arr,qjx

(']qjx', array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

<i>np.savez</i> saves multiple arrays. Pass them as **kwds, else they are named arr_0, arr_1, etc. They are as a dictionary-like object. Individual arrays are lazy loaded (ie, only when you explicitly access it by its name) based on the argument name used when saving


In [ ]:
np.savez("array_archive.npz", qjx, a=qjx, b=qjx) #or np.savez_compressed()

In [ ]:
arch = np.load("array_archive.npz")
arch.files #see the 'keys' #arch["b"]keys()

['a', 'b', 'arr_0']

In [ ]:
!rm some_array.npy
!rm array_archive.npz
!rm arrays_compressed.npz

In [ ]:
#More on linear algebra: we have already seen transpose and matrix multiplication
#from numpy.linalg import inv, qr
X = rng.standard_normal((5, 5))
mat = X.T @ X
np.linalg.inv(X) #matrix inverse
#mat @ inv(mat)

array([[-6.82650243, -5.81007558,  0.81049555, -0.7701553 ,  5.55895535],
       [-5.48546897, -4.66692999,  1.1452104 , -0.05889701,  4.1902381 ],
       [-3.17514595, -2.58491202,  0.54514667, -0.21039896,  2.01035052],
       [-3.74450693, -2.88217492,  0.78509641, -0.37930286,  2.90868905],
       [ 3.9887176 ,  2.92335784, -0.32076397,  0.41809718, -3.01356466]])

<table border="1" cellpadding="6" cellspacing="0">
  <thead>
    <tr><th>Function</th><th>Description</th></tr>
  </thead>
  <tbody>
    <tr><td>diag</td><td>Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array,<br>
    or convert a 1D array into a square matrix with zeros on the off-diagonal</td></tr>
    <tr><td>dot</td><td>Matrix multiplication</td></tr>
    <tr><td>trace</td><td>Compute the sum of the diagonal elements</td></tr>
    <tr><td>det</td><td>Compute the matrix determinant</td></tr>
    <tr><td>eig</td><td>Compute the eigenvalues and eigenvectors of a square matrix</td></tr>
    <tr><td>inv</td><td>Compute the inverse of a square matrix</td></tr>
    <tr><td>pinv</td><td>Compute the Moore-Penrose pseudoinverse of a matrix</td></tr>
    <tr><td>qr</td><td>Compute the QR decomposition</td></tr>
    <tr><td>svd</td><td>Compute the singular value decomposition (SVD)</td></tr>
    <tr><td>solve</td><td>Solve the linear system Ax = b for x, where A is a square matrix</td></tr>
    <tr><td>lstsq</td><td>Compute the least-squares solution to Ax = b</td></tr>
  </tbody>
</table>

Random walk simulation: start at 0, at each step go up (+1) or down (-1) with equal probability

In [ ]:
import random
position = 0
walk = [position]
nsteps = 1000
for _ in range(nsteps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

In [ ]:
#faster in np
nsteps = 1000
rng = np.random.default_rng(seed=12345)  # fresh random generator
draws = rng.integers(0, 2, size=nsteps)
steps = np.where(draws == 0, 1, -1)
walk = steps.cumsum()

In [ ]:
#plt.plot(walk[:68])

In [ ]:
walk.min(), walk.max()

(np.int64(-8), np.int64(50))

In [ ]:
(np.abs(walk) >= 10).argmax() #how long it took to be 10+ steps away from 0

In [ ]:
#simulate 5e3 random walks with minimal code modification
nwalks = 5000
nsteps = 1000
draws = rng.integers(0, 2, size=(nwalks, nsteps))
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(axis=1)
walks

array([[  1,   2,   3, ...,  22,  23,  22],
       [  1,   0,  -1, ..., -50, -49, -48],
       [  1,   2,   3, ...,  50,  49,  48],
       ...,
       [ -1,  -2,  -1, ..., -10,  -9, -10],
       [ -1,  -2,  -3, ...,   8,   9,   8],
       [ -1,   0,   1, ...,  -4,  -3,  -2]])

In [ ]:
walks.max(),walks.min() #overall across all walks

(np.int64(114), np.int64(-120))

In [ ]:
#find the the time per walk to reach +/-30. Not all walks get there
hits30 = (np.abs(walks) >= 30).any(axis=1)
hits30
hits30.sum() # Number that hit 30 or -30

np.int64(3395)

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(axis=1)
crossing_times

array([201, 491, 283, ..., 219, 259, 541])

In [ ]:
crossing_times.mean()

We can also experiment with other distributions for the steps, besides +/- 1 with equal prob, this is the only line to change:

In [ ]:
draws = 0.25 * rng.standard_normal((nwalks, nsteps))